### ISSUE TITLE
Bug in Util.Substitute

### ISSUE THREAD

**Issue by JohnDuncanScott** [fabioravila/rivescript-csharp#4]
[begin.txt](https://github.com/fabioravila/rivescript-csharp/files/439595/begin.txt)
[main.txt](https://github.com/fabioravila/rivescript-csharp/files/439594/main.txt)

The method of using Rot13 to do substitutions does not seem to be robust.

Attached are the RS files I was using. This is taken partially from the Eliza template on the RiveScript website.

Input: he's an idiot
Actual output: Why are you concerned over my vfbus31tor an idiot?
Expected output: Use: https://www.rivescript.com/try with the Eliza template (the default one) - this shouldn't match anything at all

**Comment by fabioravila** [comment]
Fixed tnks for your help
I just leav Rot13 behind and use a indexed placeholder like JS version.
